### ISSUE TITLE
Add power led on the FRONT of the alu

### ISSUE THREAD

**Issue by izeek182** [Schmorbonium/ECE-4710#11]

**Comment by dknelson9876** [comment]
@izeek182 what was the purpose of this? Just on the rail to show that power is present?

**Comment by dknelson9876** [comment]
Confirmed destination as power rails, and Alex did the math for the correct resistance [here](https://schmorbonium.github.io/ECE-4710/?ActivePage=partDoc). Action waiting time at PC
